_target_: ctd.task_modeling.simulator.neural_simulator.NeuralDataSimulator
neuron_dict:
  n_neurons_heldin: 500
  n_neurons_heldout: 600
embed_dict:
  rect_func: exp
  fr_scaling: 100.0
  target_mean_rates: .004
noise_dict:
  obs_noise: pseudoPoisson
  dispersion: 1.0
