raster_plot:
  _target_: ctd.data_modeling.callbacks.LFADS.callbacks.RasterPlot
  log_every_n_epochs: 10
tune_report_callback:
  _target_: ray.tune.integration.pytorch_lightning.TuneReportCallback
  metrics:
    loss: valid/loss
trajectory_plot:
  _target_: ctd.data_modeling.callbacks.LFADS.callbacks.TrajectoryPlot
  log_every_n_epochs: 10
dt_metrics:
  _target_: ctd.data_modeling.callbacks.LFADS.callbacks.DTMetricsCallback
  log_every_n_epochs: 10
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: valid/recon_smth
  mode: min
  save_top_k: 1
  save_last: True
  verbose: False
  dirpath: lightning_checkpoints
  auto_insert_metric_name: False
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: valid/recon_smth
  mode: min
  patience: 200
  min_delta: 0
learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
