_target_: ctd.data_modeling.models.SAE.node.NODELatentSAE
dataset: NBFF

encoder_size: 100
encoder_window: -1

heldin_size: 500
heldout_size: 600
latent_size: 3
input_size: 3

dropout: 0.05

vf_hidden_size: 128
vf_num_layers: 6

lr: 1e-3

weight_decay: 0
