_target_: ctd.data_modeling.models.SAE.vanilla_rnn.RNNLatentSAE
dataset: NBFF

encoder_size: 100
encoder_window: -1

heldin_size: 50
heldout_size: 60
latent_size: 128
input_size: 3

weight_decay: 0
lr: 5e-3

dropout: 0.05
